language: node_js
node_js:
 - "9"
 - "8"

cache:
  directories:
    - "node_modules"

addons:
  apt:
    update: true

sudo: enabled

# after_success:
#   - wget https://raw.githubusercontent.com/DS-Development/delet/master/ci/travis/send.sh
#   - chmod +x send.sh
#   - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DS-Development/delet/master/ci/travis/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL